version: '3.5'

services:
  larabook:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: larabook
    environment:
      APACHE_RUN_USER: "#${UID}"
      APACHE_RUN_GROUP: "#${UID}"
      VIRTUAL_HOST: local.larabook.com
      VIRTUAL_PORT: 8000
    volumes:
      - .:/var/www/html
    expose:
      - 80  
    networks:
      backend:
        aliases:
          - larabook
      default:

  mysql-db:
    image: mysql:5.7.22
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./run/pma
    ports:
      - "9000:80"
    networks:
      backend:
        aliases:
          - pma

networks:
  backend:
    name: backend-network
  default:
    external:
      name: nginx-proxy