version: '3.5'

services:
  larabook:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: larabook
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - ${HOST_PORT}:80
    networks:
      backend:
        aliases:
          - larabook

  mysql-db:
    image: mysql:5.7.22
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network